name: Test LeetCode Problems

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-problems:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        problem: [
          "1 - Two sum",
          "2 - Add Two Numbers", 
          "9 - Palindrome Number"
        ]
        language: [java, python, typescript]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      if: matrix.language == "java"
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Set up Python
      if: matrix.language == "python"
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Set up Node.js
      if: matrix.language == "typescript"
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install TypeScript dependencies
      if: matrix.language == "typescript"
      run: |
        cd "problems/${{ matrix.problem }}/tests"
        npm install

    - name: Test Java Solution
      if: matrix.language == "java"
      run: |
        cd "problems/${{ matrix.problem }}"
        # Compile the solution
        javac Solution.java
        # Compile the test
        cd tests
        javac -cp ".:../Solution.class" TestSolution.java
        # Run tests
        java -cp ".:../Solution.class" TestSolution test-cases.json

    - name: Test Python Solution
      if: matrix.language == "python"
      run: |
        cd "problems/${{ matrix.problem }}/tests"
        python test_solution.py test-cases.json

    - name: Test TypeScript Solution
      if: matrix.language == "typescript"
      run: |
        cd "problems/${{ matrix.problem }}/tests"
        # Compile TypeScript
        npx tsc test_solution.ts
        # Run the compiled JavaScript
        node test_solution.js test-cases.json

  test-all-languages:
    runs-on: ubuntu-latest
    needs: test-problems
    if: always()
    
    steps:
    - name: Check test results
      run: |
        echo "All problem tests completed"
        echo "Check the individual job results above for detailed test outputs"
